[package]
name = "bufy-domain"
version = "0.1.0"
edition = "2021"

[lib]
name = "bufy_domain"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4", features = ["serde", "v4"] }
