[package]
name = "bufy-storage-json"
version = "0.1.0"
edition = "2021"

[lib]
name = "bufy_storage_json"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bufy-domain = { path = "../bufy-domain" }
bufy-core = { path = "../bufy-core" }
