[package]
name = "bufy-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "bufy_core"
path = "src/lib.rs"

[dependencies]
bufy-domain = { path = "../bufy-domain" }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
uuid = { version = "1.4", features = ["serde", "v4"] }
